language: python

python:
 - 2.7
 - 3.5
 - nightly
 - pypy
 - pypy3

matrix:
 allow_failures:
  - python: 3.2
  - python: 3.3
  - python: 3.4
  - python: 3.5
  - python: nightly
  - python: pypy3

script: python setup.py test

